In [1]:
import random,os
import pandas as pd
import numpy as np
import missingno as msno
from Data_cleaning_utils import perform_data_cleaning
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder,StandardScaler
from sklearn.compose import ColumnTransformer,TransformedTargetRegressor
from sklearn.pipeline import Pipeline
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer,KNNImputer,IterativeImputer
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_validate, cross_val_predict
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, StackingRegressor
from sklearn.tree import DecisionTreeRegressor
from catboost import CatBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn import set_config
set_config(transform_output='pandas')
import optuna as optuna


def seed_everything(seed=0):
    random.seed(seed)
    np.random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)

seed = 0
seed_everything(seed)

import dagshub
dagshub.init(repo_owner='shapniljoy', repo_name='delivery-time-prediction', mlflow=True)

import mlflow
mlflow.set_tracking_uri("https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow")
mlflow.set_experiment('StackingRegressor HP Tuning')

Accessing as shapniljoy

Initialized MLflow to track repo "shapniljoy/delivery-time-prediction"

Repository shapniljoy/delivery-time-prediction initialized!

<Experiment: artifact_location='mlflow-artifacts:/751c2160b14b43f4a222918cbcadbffb', creation_time=1782111186062, experiment_id='6', last_update_time=1782111186062, lifecycle_stage='active', name='StackingRegressor HP Tuning', tags={'mlflow.experimentKind': 'custom_model_development'}, trace_location=None, workspace='default'>

Previously we have run 3 different models, 2 boosting algorithms CatboostRegressor and LightGBMRegressor and 1 bagging algorithm Random forest.  
The final Cross validation scores after dropping missing values and With Numerical columns are,  
(1) LightGBMRegressor,  
Training cv mae : 2.45 , Test cv mae : 3.09  
(2) CatboostRegressor,  
Training cv mae : 2.60 , Test cv mae : 3.13  
(3) RandomForestRegressor,  
Training cv mae : 2.54 , Test cv mae : 3.08  


Although all of the 3 models are slightly overfitting in the data and showing almost simillar type of mae cv score, we shall choose the models with lower gap in the training cv and test cv.
So we choose CatboostRegressor and RandomForestRegressor for further StackingRegressor method.  
It is also adviseble to use 2 different type of algorithms in stacking regressor to get mor robust results and hyperparameter tuning.

In [8]:
data = pd.read_csv(r"C:/Users/User/delivery-time-prediction/data/raw/swiggy.csv")
df = perform_data_cleaning(data)
df = df.dropna()

df = df.drop(columns=['rider_id','restaurant_lat', 'restaurant_long',
       'delivery_lat', 'delivery_long', 'city_name', 'order_time_hour','age',
        'ratings','distance_km','pickup_time','day','month'])
x = df.drop(columns=['time'])
y = df['time'] 

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=seed)

print(f"Training data: {x_train.shape} and {y_train.shape}", '\n')
print(f"Testing data: {x_test.shape} and {y_test.shape}", '\n')

Training data: (30156, 15) and (30156,)

Testing data: (7539, 15) and (7539,)

In [9]:
rating_order = ['less than 4','4-4.5','4.5-5']

distance_order = ['short','medium','long','very_long']

city_type_order = ['Semi-Urban','Urban','Metropolitan']

pickup_time_order = ['5 minutes','10 minutes','15 minutes']

ordinal_encoding = OrdinalEncoder(categories=[rating_order,distance_order,city_type_order,pickup_time_order],
                                  handle_unknown='use_encoded_value', unknown_value=-999)


preprocessor = ColumnTransformer([
        ('OE',ordinal_encoding, ['ratings_cat','distance_km_cat','city_type','pickup_time_cat']),
        ('OHE', OneHotEncoder(drop='first',sparse_output=False), ['vehicle_type','order_type','day_of_week',
                                                                  'age_cat','weather','traffic','festival','time_of_day']),
        ],remainder='passthrough')

In [10]:
lgbm_params = {
 'n_estimators': 1940,
 'max_depth': 7,
 'num_leaves': 57,
 'min_child_samples': 228,
 'colsample_bytree': 0.8452545147323064,
 'learning_rate': 0.046640660322683554,
 'reg_alpha': 0.020341454480246005,
 'reg_lambda': 0.10776961230711216,
 'boosting_type': 'dart',
 'subsample': 0.9481361810641186
}

RF_params = {
    'n_estimators': 641,
    'max_depth': 13,
    'min_samples_split': 6,
    'min_samples_leaf': 6,
    'max_features': None,
    'max_samples': 0.992036436296416
}

x_train_preprocessed = preprocessor.fit_transform(x_train)

lgbm = LGBMRegressor(**lgbm_params,verbose=-1)
lgbm_predicted = cross_val_predict(lgbm, x_train_preprocessed, y_train,
                                  cv=KFold(n_splits=5,shuffle=True,random_state=seed),n_jobs=-1,verbose=False)

rf = RandomForestRegressor(**RF_params)
rf_predicted = cross_val_predict(rf, x_train_preprocessed, y_train,
                                cv=KFold(n_splits=5,shuffle=True,random_state=seed),n_jobs=-1,verbose=False)

In [13]:
meta_predicted = np.stack((lgbm_predicted,rf_predicted),axis=1)
meta_predicted

array([[21.65329502, 22.90266685],
       [16.93845254, 16.6351303 ],
       [17.91516069, 19.7005672 ],
       ...,
       [24.52027423, 24.53455992],
       [26.77802184, 25.81897452],
       [31.11906291, 33.53336038]], shape=(30156, 2))

In [18]:
def objective(trial):

    with mlflow.start_run(nested=True,run_name=f"trial_{trial.number}"):

        stacking_models = trial.suggest_categorical('stacking_models', ['LR','Lasso','Ridge','DT'])

        if stacking_models == 'LR':
            estimator = LinearRegression()
            
        elif stacking_models == 'DT':

            max_depth = trial.suggest_int('max_depth', 4, 10)
            max_leaf_nodes = trial.suggest_int('max_leaf_nodes', 5, 10)
            min_samples_split = trial.suggest_int('min_samples_split', 5, 20)
            min_samples_leaf = trial.suggest_int('min_samples_leaf', 5, 10)
            max_features = trial.suggest_categorical('max_features', ['sqrt', 'log2', None])

            estimator = DecisionTreeRegressor(max_depth=max_depth, max_leaf_nodes=max_leaf_nodes,
                                            min_samples_split=min_samples_split,
                                            min_samples_leaf=min_samples_leaf,
                                            max_features=max_features, random_state=seed)
        
        elif stacking_models == 'Lasso':

            alpha = trial.suggest_float('alpha', 0.001,0.5, log=True)

            estimator = Lasso(alpha=alpha ,random_state=seed)

        elif stacking_models == 'Ridge':
            alpha = trial.suggest_float('alpha', 0.001,0.5, log=True)
            solver = trial.suggest_categorical('solver', ['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga'])

            estimator = Ridge(alpha=alpha,solver=solver ,random_state=seed)
        
        
        # model = Pipeline([
            # ('preprocessor',preprocessor),
            # ('Stacking_estimator', estimator)
        # ])  

        cv_score = cross_validate(estimator, meta_predicted, y_train, cv=KFold(n_splits=5,shuffle=True,random_state=seed), 
                                scoring='neg_mean_absolute_error',verbose=False,n_jobs=-1,return_train_score=True)
        
        trial.set_user_attr('train_cv',np.mean(cv_score['train_score']))
        trial.set_user_attr('val_cv',np.mean(cv_score['test_score']))
        
        mlflow.log_params(trial.params)
        mlflow.log_metric('train_cv_score',np.mean(cv_score['train_score']))
        mlflow.log_metric('val_cv_score',np.mean(cv_score['test_score']))
            
        return np.mean(cv_score['test_score'])


study = optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler(seed=seed),
                            study_name='StackingRegressor Hyperparameter Tuning')
    
with mlflow.start_run(run_name='StackingRegressor') as parent :
    study.optimize(objective,n_trials=30,show_progress_bar=True)

    mlflow.log_metric('StackingRegressor best Score',study.best_value)
    mlflow.log_params(study.best_params)

    print('Best parameters:', study.best_params)
    print('Best score:', study.best_value, '\n')

[I 2026-06-22 13:40:21,348] A new study created in memory with name: StackingRegressor Hyperparameter Tuning

  0%|          | 0/30 [00:00<?, ?it/s]

🏃 View run trial_0 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/672589ba77664e98a3c64d5c2684d856
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:40:27,840] Trial 0 finished with value: -3.5529375168940254 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.013913346327363716}. Best is trial 0 with value: -3.5529375168940254.
🏃 View run trial_1 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/eb28e14ca092485982d8511764e066ac
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:40:32,414] Trial 1 finished with value: -3.69256445318195 and parameters: {'stacking_models': 'DT', 'max_depth': 6, 'max_leaf_nodes': 9, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: -3.5529375168940254.
🏃 View run trial_2 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/a0cf93dee30e4c01a6a1e46d33b531aa
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:40:36,979] Trial 2 finished with value: -3.69256445318195 and parameters: {'stacking_models': 'DT', 'max_depth': 10, 'max_leaf_nodes': 9, 'min_samples_split': 12, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: -3.5529375168940254.
🏃 View run trial_3 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/0fe72db6342b4f94a383322e0e86923e
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:40:39,624] Trial 3 finished with value: -3.552899222071318 and parameters: {'stacking_models': 'LR'}. Best is trial 3 with value: -3.552899222071318.
🏃 View run trial_4 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/554bb5c2da28432db970fe7e2fe9f6f2
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:40:43,400] Trial 4 finished with value: -3.552899222071318 and parameters: {'stacking_models': 'LR'}. Best is trial 3 with value: -3.552899222071318.
🏃 View run trial_5 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/c7d5b1a3af554b6f8a0a122ece3318e4
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:40:47,576] Trial 5 finished with value: -3.7354463730354786 and parameters: {'stacking_models': 'DT', 'max_depth': 8, 'max_leaf_nodes': 7, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 3 with value: -3.552899222071318.
🏃 View run trial_6 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/0ebe927f94e4428588b9ec3897bd2de1
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:40:54,592] Trial 6 finished with value: -3.7354463730354786 and parameters: {'stacking_models': 'DT', 'max_depth': 7, 'max_leaf_nodes': 7, 'min_samples_split': 20, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 3 with value: -3.552899222071318.
🏃 View run trial_7 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/5335f6a1b4f247c1a771a778bb76fbe9
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:41:06,616] Trial 7 finished with value: -3.5529573045304823 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.001985633975248891}. Best is trial 3 with value: -3.552899222071318.
🏃 View run trial_8 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/78a98ae8486d4ab6a5a9f63893fd4a3c
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:41:23,284] Trial 8 finished with value: -3.552899222071318 and parameters: {'stacking_models': 'LR'}. Best is trial 3 with value: -3.552899222071318.
🏃 View run trial_9 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/75da867c8f974bb8a920b14d1665d187
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:41:26,589] Trial 9 finished with value: -3.5528991755234527 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.4319513210123975, 'solver': 'svd'}. Best is trial 9 with value: -3.5528991755234527.
🏃 View run trial_10 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/872bf546aba74cfb9675d5634d31fc02
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:41:46,612] Trial 10 finished with value: -3.552899172640884 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.45870124335700735, 'solver': 'svd'}. Best is trial 10 with value: -3.552899172640884.
🏃 View run trial_11 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/c9bbc27d7e82459aa95f2567baf3f369
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:41:52,869] Trial 11 finished with value: -3.5528991777439423 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.41134545476217693, 'solver': 'svd'}. Best is trial 10 with value: -3.552899172640884.
🏃 View run trial_12 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/3da546d6e6b54dbd9e4514332df74832
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:41:56,038] Trial 12 finished with value: -3.552899172485364 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.4601444565858987, 'solver': 'svd'}. Best is trial 12 with value: -3.552899172485364.
🏃 View run trial_13 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/2b222905218b479db3202ba34d03bdff
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:42:06,597] Trial 13 finished with value: -3.5528992118486387 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.0948623806716555, 'solver': 'svd'}. Best is trial 12 with value: -3.552899172485364.
🏃 View run trial_14 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/06637f7a8e6b4612b2f424a508dc53f2
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:42:22,588] Trial 14 finished with value: -3.552899213709342 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.07759576166581628, 'solver': 'auto'}. Best is trial 12 with value: -3.552899172485364.
🏃 View run trial_15 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/d7ea3c8840cc4919b92ae2d2dd2e0d15
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:42:31,216] Trial 15 finished with value: -3.5528959800501925 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.11739048439002037, 'solver': 'sag'}. Best is trial 15 with value: -3.5528959800501925.
🏃 View run trial_16 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/f296c73dc52a43ae988fe69ae64f493f
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:42:37,641] Trial 16 finished with value: -3.552895982323755 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.09296593655053999, 'solver': 'sag'}. Best is trial 15 with value: -3.5528959800501925.
🏃 View run trial_17 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/500210ca86594ebbaf7e84f961dec58d
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:42:49,725] Trial 17 finished with value: -3.5528959862941774 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.05031192380775798, 'solver': 'sag'}. Best is trial 15 with value: -3.5528959800501925.
🏃 View run trial_18 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/58f127f13da04698a56c9905d93c28bf
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:43:01,744] Trial 18 finished with value: -3.5528959894554837 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.01634990666693574, 'solver': 'sag'}. Best is trial 15 with value: -3.5528959800501925.
🏃 View run trial_19 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/41a3db4181ae4cdea75aa736a4a0f3ed
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:43:09,720] Trial 19 finished with value: -3.5527596173195577 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.1317000164933719}. Best is trial 19 with value: -3.5527596173195577.
🏃 View run trial_20 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/789aa2e534b14641a579c11308c13122
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:43:27,047] Trial 20 finished with value: -3.552720011970642 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.16216749190844468}. Best is trial 20 with value: -3.552720011970642.
🏃 View run trial_21 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/e5a3fe63a35a4129949a61efa9e4ec99
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:43:37,766] Trial 21 finished with value: -3.5527050612536692 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.1745887528876206}. Best is trial 21 with value: -3.5527050612536692.
🏃 View run trial_22 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/7efb01b7463146bf9b2b6798abc1cc77
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:43:50,413] Trial 22 finished with value: -3.552687782590259 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.18934529054630375}. Best is trial 22 with value: -3.552687782590259.
🏃 View run trial_23 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/4266532c8f444e3ca116a1f8d4025059
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:44:02,424] Trial 23 finished with value: -3.5529061791645353 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.03329025666710916}. Best is trial 22 with value: -3.552687782590259.
🏃 View run trial_24 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/581e1f5345664c568caa35d4db6cbee8
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:44:13,753] Trial 24 finished with value: -3.5527037449988925 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.17569817122892967}. Best is trial 22 with value: -3.552687782590259.
🏃 View run trial_25 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/57821dad79384023886c71706ec139bf
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:44:26,618] Trial 25 finished with value: -3.5526155555312826 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.25566340860388165}. Best is trial 25 with value: -3.5526155555312826.
🏃 View run trial_26 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/785ff081443f4480b5a8840af41a5f6d
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:44:34,027] Trial 26 finished with value: -3.5529480704174476 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.0075346446360053205}. Best is trial 25 with value: -3.5526155555312826.
🏃 View run trial_27 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/96b7cc6af5fb49248297262f6c16086d
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:44:39,050] Trial 27 finished with value: -3.5526387504476142 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.23331873484855345}. Best is trial 25 with value: -3.5526155555312826.
🏃 View run trial_28 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/5452380389e04e468daae6914cf7d49f
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:44:45,770] Trial 28 finished with value: -3.552637954833751 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.23405592995195934}. Best is trial 25 with value: -3.5526155555312826.
🏃 View run trial_29 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/3293f82afa964a778d2588ce13d05dc8
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 13:44:57,774] Trial 29 finished with value: -3.5526105932152463 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.2606044403283886}. Best is trial 29 with value: -3.5526105932152463.
Best parameters: {'stacking_models': 'Lasso', 'alpha': 0.2606044403283886}
Best score: -3.5526105932152463

🏃 View run StackingRegressor at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/4c6589bcf1ec4bbdb03abc8473a2cdc0
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6

In [21]:
study.trials_dataframe()[['user_attrs_train_cv','user_attrs_val_cv','params_stacking_models']].sort_values(by='user_attrs_val_cv',ascending=False)

    user_attrs_train_cv  user_attrs_val_cv params_stacking_models
29            -3.552161          -3.552611                  Lasso
25            -3.552166          -3.552616                  Lasso
28            -3.552188          -3.552638                  Lasso
27            -3.552188          -3.552639                  Lasso
22            -3.552236          -3.552688                  Lasso
24            -3.552252          -3.552704                  Lasso
21            -3.552253          -3.552705                  Lasso
20            -3.552268          -3.552720                  Lasso
19            -3.552307          -3.552760                  Lasso
15            -3.552444          -3.552896                  Ridge
16            -3.552444          -3.552896                  Ridge
17            -3.552444          -3.552896                  Ridge
18            -3.552444          -3.552896                  Ridge
12            -3.552446          -3.552899                  Ridge
10            -3.552446          -3.552899                  Ridge
9             -3.552446          -3.552899                  Ridge
11            -3.552446          -3.552899                  Ridge
13            -3.552446          -3.552899                  Ridge
14            -3.552446          -3.552899                  Ridge
4             -3.552446          -3.552899                     LR
8             -3.552446          -3.552899                     LR
3             -3.552446          -3.552899                     LR
23            -3.552453          -3.552906                  Lasso
0             -3.552485          -3.552938                  Lasso
26            -3.552496          -3.552948                  Lasso
7             -3.552505          -3.552957                  Lasso
2             -3.665390          -3.692564                     DT
1             -3.665390          -3.692564                     DT
6             -3.713573          -3.735446                     DT
5             -3.713573          -3.735446                     DT

In [22]:
study.best_params

{'stacking_models': 'Lasso', 'alpha': 0.2606044403283886}

# Optuna after dropping missing values and With Numerical columns

In [2]:
data = pd.read_csv(r"C:/Users/User/delivery-time-prediction/data/raw/swiggy.csv")
df = perform_data_cleaning(data)
df = df.dropna()

df = df.drop(columns=['rider_id','restaurant_lat', 'restaurant_long',
       'delivery_lat', 'delivery_long', 'city_name', 'order_time_hour','day','month',
        'age_cat','ratings_cat','distance_km_cat','pickup_time_cat'])
x = df.drop(columns=['time'])
y = df['time'] 

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=seed)

print(f"Training data: {x_train.shape} and {y_train.shape}", '\n')
print(f"Testing data: {x_test.shape} and {y_test.shape}", '\n')

Training data: (30156, 15) and (30156,)

Testing data: (7539, 15) and (7539,)

In [3]:

numerical_cols = ['age','ratings','distance_km','pickup_time']

city_type_order = ['Semi-Urban','Urban','Metropolitan']

ordinal_encoding = OrdinalEncoder(categories=[city_type_order],
                                  handle_unknown='use_encoded_value', unknown_value=-999)


preprocessor = ColumnTransformer([
        ('OE',ordinal_encoding, ['city_type']),
        ('OHE', OneHotEncoder(drop='first',sparse_output=False), ['vehicle_type','order_type','day_of_week',
                                                                  'weather','traffic','festival','time_of_day']),
        ('scaling',StandardScaler(),numerical_cols),
        ],remainder='passthrough')

In [6]:
catboost_params = {'iterations': 618, 
                  'depth': 7, 
                  'learning_rate': 0.029550509331092316, 
                  'l2_leaf_reg': 31.153463513382516, 
                  'random_strength': 1, 
                  'bagging_temperature': 0.7163272041185655, 
                  'border_count': 96, 
                  'grow_policy': 'Depthwise', 
                  'max_ctr_complexity': 7}

RF_params = {'n_estimators': 902,
            'max_depth': 14,
            'min_samples_split': 10,
            'min_samples_leaf': 7,
            'max_features': None,
            'max_samples': 0.9857978714826628}

x_train_preprocessed = preprocessor.fit_transform(x_train)

catboost_model = CatBoostRegressor(**catboost_params,random_state=seed)
catboost_predicted = cross_val_predict(catboost_model,x_train_preprocessed,y_train,cv=KFold(n_splits=5,shuffle=True,random_state=seed))

rf_model = RandomForestRegressor(**RF_params,bootstrap=True,random_state=seed,verbose=False)
rf_predicted = cross_val_predict(rf_model,x_train_preprocessed,y_train,cv=KFold(n_splits=5,shuffle=True,random_state=seed))

x_predicted = np.stack([catboost_predicted,rf_predicted],axis=1)
x_predicted

0:	learn: 9.1994034	total: 6.92ms	remaining: 4.27s
1:	learn: 9.0383543	total: 13.5ms	remaining: 4.15s
2:	learn: 8.8863865	total: 20.5ms	remaining: 4.2s
3:	learn: 8.7417051	total: 27.2ms	remaining: 4.18s
4:	learn: 8.5999262	total: 34.6ms	remaining: 4.25s
5:	learn: 8.4591826	total: 40.8ms	remaining: 4.17s
6:	learn: 8.3208659	total: 49.5ms	remaining: 4.32s
7:	learn: 8.1930455	total: 56.3ms	remaining: 4.29s
8:	learn: 8.0687367	total: 63.2ms	remaining: 4.27s
9:	learn: 7.9486193	total: 70.5ms	remaining: 4.29s
10:	learn: 7.8329411	total: 77.2ms	remaining: 4.26s
11:	learn: 7.7189044	total: 83.7ms	remaining: 4.23s
12:	learn: 7.6171802	total: 89.5ms	remaining: 4.16s
13:	learn: 7.5214851	total: 96.3ms	remaining: 4.16s
14:	learn: 7.4245420	total: 103ms	remaining: 4.12s
15:	learn: 7.3280866	total: 109ms	remaining: 4.12s
16:	learn: 7.2364880	total: 116ms	remaining: 4.08s
17:	learn: 7.1486789	total: 122ms	remaining: 4.08s
18:	learn: 7.0652945	total: 129ms	remaining: 4.05s
19:	learn: 6.9836994	total: 135ms	remaining: 4.03s
20:	learn: 6.9061203	total: 141ms	remaining: 4.01s
21:	learn: 6.8268612	total: 148ms	remaining: 4s
22:	learn: 6.7544367	total: 154ms	remaining: 3.99s
23:	learn: 6.6857993	total: 161ms	remaining: 3.98s
24:	learn: 6.6117358	total: 167ms	remaining: 3.95s
25:	learn: 6.5435854	total: 173ms	remaining: 3.94s
26:	learn: 6.4753799	total: 180ms	remaining: 3.93s
27:	learn: 6.4119055	total: 187ms	remaining: 3.94s
28:	learn: 6.3474745	total: 193ms	remaining: 3.92s
29:	learn: 6.2894002	total: 200ms	remaining: 3.92s
30:	learn: 6.2305428	total: 206ms	remaining: 3.91s
31:	learn: 6.1784793	total: 213ms	remaining: 3.9s
32:	learn: 6.1240548	total: 219ms	remaining: 3.88s
33:	learn: 6.0721775	total: 225ms	remaining: 3.87s
34:	learn: 6.0221097	total: 231ms	remaining: 3.85s
35:	learn: 5.9755571	total: 238ms	remaining: 3.85s
36:	learn: 5.9301925	total: 243ms	remaining: 3.82s
37:	learn: 5.8808461	total: 249ms	remaining: 3.81s
38:	learn: 5.8382006	total: 256ms	remaining: 3.8s
39:	learn: 5.7931087	total: 262ms	remaining: 3.78s
40:	learn: 5.7451994	total: 268ms	remaining: 3.77s
41:	learn: 5.7032112	total: 274ms	remaining: 3.76s
42:	learn: 5.6656663	total: 280ms	remaining: 3.75s
43:	learn: 5.6260613	total: 286ms	remaining: 3.73s
44:	learn: 5.5851787	total: 292ms	remaining: 3.72s
45:	learn: 5.5489571	total: 298ms	remaining: 3.7s
46:	learn: 5.5158596	total: 306ms	remaining: 3.71s
47:	learn: 5.4791528	total: 312ms	remaining: 3.7s
48:	learn: 5.4404445	total: 319ms	remaining: 3.71s
49:	learn: 5.4073294	total: 325ms	remaining: 3.69s
50:	learn: 5.3722767	total: 331ms	remaining: 3.69s
51:	learn: 5.3455591	total: 337ms	remaining: 3.67s
52:	learn: 5.3191251	total: 343ms	remaining: 3.66s
53:	learn: 5.2878157	total: 350ms	remaining: 3.66s
54:	learn: 5.2653915	total: 357ms	remaining: 3.65s
55:	learn: 5.2410124	total: 363ms	remaining: 3.65s
56:	learn: 5.2138823	total: 370ms	remaining: 3.64s
57:	learn: 5.1909468	total: 376ms	remaining: 3.63s
58:	learn: 5.1664671	total: 383ms	remaining: 3.62s
59:	learn: 5.1393170	total: 388ms	remaining: 3.61s
60:	learn: 5.1198566	total: 395ms	remaining: 3.61s
61:	learn: 5.0971196	total: 401ms	remaining: 3.59s
62:	learn: 5.0724554	total: 407ms	remaining: 3.59s
63:	learn: 5.0537484	total: 413ms	remaining: 3.57s
64:	learn: 5.0346195	total: 420ms	remaining: 3.57s
65:	learn: 5.0065821	total: 428ms	remaining: 3.58s
66:	learn: 4.9806349	total: 436ms	remaining: 3.59s
67:	learn: 4.9626685	total: 443ms	remaining: 3.58s
68:	learn: 4.9440178	total: 450ms	remaining: 3.58s
69:	learn: 4.9264123	total: 457ms	remaining: 3.58s
70:	learn: 4.9099037	total: 465ms	remaining: 3.58s
71:	learn: 4.8946424	total: 471ms	remaining: 3.57s
72:	learn: 4.8769933	total: 478ms	remaining: 3.57s
73:	learn: 4.8561857	total: 487ms	remaining: 3.58s
74:	learn: 4.8376342	total: 494ms	remaining: 3.57s
75:	learn: 4.8208448	total: 501ms	remaining: 3.57s
76:	learn: 4.8090270	total: 507ms	remaining: 3.56s
77:	learn: 4.7980166	total: 514ms	remaining: 3.56s
78:	learn: 4.7804890	total: 522ms	remaining: 3.56s
79:	learn: 4.7580002	total: 529ms	remaining: 3.56s
80:	learn: 4.7445595	total: 536ms	remaining: 3.55s
81:	learn: 4.7214194	total: 543ms	remaining: 3.55s
82:	learn: 4.7108170	total: 549ms	remaining: 3.54s
83:	learn: 4.6907973	total: 557ms	remaining: 3.54s
84:	learn: 4.6746727	total: 564ms	remaining: 3.54s
85:	learn: 4.6631874	total: 571ms	remaining: 3.53s
86:	learn: 4.6485679	total: 578ms	remaining: 3.53s
87:	learn: 4.6297918	total: 584ms	remaining: 3.52s
88:	learn: 4.6158912	total: 591ms	remaining: 3.51s
89:	learn: 4.6041637	total: 598ms	remaining: 3.51s
90:	learn: 4.5956827	total: 610ms	remaining: 3.53s
91:	learn: 4.5860464	total: 619ms	remaining: 3.54s
92:	learn: 4.5685564	total: 629ms	remaining: 3.55s
93:	learn: 4.5502773	total: 636ms	remaining: 3.55s
94:	learn: 4.5371856	total: 644ms	remaining: 3.54s
95:	learn: 4.5256239	total: 650ms	remaining: 3.54s
96:	learn: 4.5170081	total: 659ms	remaining: 3.54s
97:	learn: 4.5047058	total: 665ms	remaining: 3.53s
98:	learn: 4.4942846	total: 672ms	remaining: 3.52s
99:	learn: 4.4864091	total: 678ms	remaining: 3.51s
100:	learn: 4.4811309	total: 684ms	remaining: 3.5s
101:	learn: 4.4702852	total: 690ms	remaining: 3.49s
102:	learn: 4.4607918	total: 696ms	remaining: 3.48s
103:	learn: 4.4455554	total: 702ms	remaining: 3.47s
104:	learn: 4.4297970	total: 709ms	remaining: 3.46s
105:	learn: 4.4230760	total: 713ms	remaining: 3.44s
106:	learn: 4.4097370	total: 720ms	remaining: 3.44s
107:	learn: 4.4009764	total: 726ms	remaining: 3.43s
108:	learn: 4.3901862	total: 733ms	remaining: 3.42s
109:	learn: 4.3843234	total: 738ms	remaining: 3.41s
110:	learn: 4.3774927	total: 745ms	remaining: 3.4s
111:	learn: 4.3729031	total: 750ms	remaining: 3.39s
112:	learn: 4.3680362	total: 757ms	remaining: 3.38s
113:	learn: 4.3630411	total: 761ms	remaining: 3.37s
114:	learn: 4.3582752	total: 767ms	remaining: 3.36s
115:	learn: 4.3544425	total: 774ms	remaining: 3.35s
116:	learn: 4.3510399	total: 780ms	remaining: 3.34s
117:	learn: 4.3391792	total: 787ms	remaining: 3.33s
118:	learn: 4.3362484	total: 792ms	remaining: 3.32s
119:	learn: 4.3260717	total: 800ms	remaining: 3.32s
120:	learn: 4.3227806	total: 806ms	remaining: 3.31s
121:	learn: 4.3191893	total: 813ms	remaining: 3.31s
122:	learn: 4.3142677	total: 820ms	remaining: 3.3s
123:	learn: 4.3097972	total: 827ms	remaining: 3.29s
124:	learn: 4.3027383	total: 834ms	remaining: 3.29s
125:	learn: 4.2980145	total: 840ms	remaining: 3.28s
126:	learn: 4.2940825	total: 846ms	remaining: 3.27s
127:	learn: 4.2918039	total: 853ms	remaining: 3.27s
128:	learn: 4.2892171	total: 860ms	remaining: 3.26s
129:	learn: 4.2834972	total: 868ms	remaining: 3.26s
130:	learn: 4.2740050	total: 874ms	remaining: 3.25s
131:	learn: 4.2696701	total: 880ms	remaining: 3.24s
132:	learn: 4.2677173	total: 886ms	remaining: 3.23s
133:	learn: 4.2646777	total: 892ms	remaining: 3.22s
134:	learn: 4.2592040	total: 899ms	remaining: 3.21s
135:	learn: 4.2551496	total: 905ms	remaining: 3.21s
136:	learn: 4.2496263	total: 911ms	remaining: 3.2s
137:	learn: 4.2463533	total: 916ms	remaining: 3.19s
138:	learn: 4.2438468	total: 922ms	remaining: 3.18s
139:	learn: 4.2415179	total: 928ms	remaining: 3.17s
140:	learn: 4.2354599	total: 934ms	remaining: 3.16s
141:	learn: 4.2329887	total: 940ms	remaining: 3.15s
142:	learn: 4.2310732	total: 946ms	remaining: 3.14s
143:	learn: 4.2265318	total: 951ms	remaining: 3.13s
144:	learn: 4.2224977	total: 956ms	remaining: 3.12s
145:	learn: 4.2178894	total: 962ms	remaining: 3.11s
146:	learn: 4.2145502	total: 969ms	remaining: 3.1s
147:	learn: 4.2117679	total: 975ms	remaining: 3.1s
148:	learn: 4.2094485	total: 981ms	remaining: 3.09s
149:	learn: 4.2056037	total: 987ms	remaining: 3.08s
150:	learn: 4.2020414	total: 992ms	remaining: 3.07s
151:	learn: 4.1998345	total: 998ms	remaining: 3.06s
152:	learn: 4.1966109	total: 1s	remaining: 3.05s
153:	learn: 4.1935263	total: 1.01s	remaining: 3.04s
154:	learn: 4.1911228	total: 1.01s	remaining: 3.03s
155:	learn: 4.1886848	total: 1.02s	remaining: 3.02s
156:	learn: 4.1852431	total: 1.03s	remaining: 3.01s
157:	learn: 4.1828577	total: 1.03s	remaining: 3s
158:	learn: 4.1770755	total: 1.04s	remaining: 3s
159:	learn: 4.1731646	total: 1.04s	remaining: 2.99s
160:	learn: 4.1709738	total: 1.05s	remaining: 2.98s
161:	learn: 4.1698942	total: 1.05s	remaining: 2.97s
162:	learn: 4.1674869	total: 1.06s	remaining: 2.96s
163:	learn: 4.1660179	total: 1.07s	remaining: 2.96s
164:	learn: 4.1605482	total: 1.07s	remaining: 2.95s
165:	learn: 4.1581447	total: 1.08s	remaining: 2.94s
166:	learn: 4.1569150	total: 1.09s	remaining: 2.93s
167:	learn: 4.1557445	total: 1.09s	remaining: 2.92s
168:	learn: 4.1530267	total: 1.1s	remaining: 2.92s
169:	learn: 4.1507504	total: 1.1s	remaining: 2.9s
170:	learn: 4.1481183	total: 1.11s	remaining: 2.9s
171:	learn: 4.1454684	total: 1.11s	remaining: 2.89s
172:	learn: 4.1411223	total: 1.12s	remaining: 2.88s
173:	learn: 4.1400557	total: 1.13s	remaining: 2.87s
174:	learn: 4.1361286	total: 1.13s	remaining: 2.86s
175:	learn: 4.1347535	total: 1.14s	remaining: 2.85s
176:	learn: 4.1325170	total: 1.14s	remaining: 2.85s
177:	learn: 4.1302910	total: 1.15s	remaining: 2.84s
178:	learn: 4.1287276	total: 1.15s	remaining: 2.83s
179:	learn: 4.1278067	total: 1.16s	remaining: 2.82s
180:	learn: 4.1266513	total: 1.16s	remaining: 2.81s
181:	learn: 4.1251757	total: 1.17s	remaining: 2.8s
182:	learn: 4.1231331	total: 1.18s	remaining: 2.79s
183:	learn: 4.1199762	total: 1.18s	remaining: 2.79s
184:	learn: 4.1191164	total: 1.19s	remaining: 2.78s
185:	learn: 4.1161001	total: 1.19s	remaining: 2.77s
186:	learn: 4.1139633	total: 1.2s	remaining: 2.76s
187:	learn: 4.1114047	total: 1.2s	remaining: 2.75s
188:	learn: 4.1094736	total: 1.21s	remaining: 2.74s
189:	learn: 4.1076797	total: 1.21s	remaining: 2.73s
190:	learn: 4.1066575	total: 1.22s	remaining: 2.73s
191:	learn: 4.1049295	total: 1.23s	remaining: 2.72s
192:	learn: 4.1034922	total: 1.23s	remaining: 2.71s
193:	learn: 4.1012066	total: 1.24s	remaining: 2.71s
194:	learn: 4.0991675	total: 1.24s	remaining: 2.7s
195:	learn: 4.0978330	total: 1.25s	remaining: 2.69s
196:	learn: 4.0967009	total: 1.25s	remaining: 2.68s
197:	learn: 4.0960741	total: 1.26s	remaining: 2.67s
198:	learn: 4.0954105	total: 1.27s	remaining: 2.67s
199:	learn: 4.0907875	total: 1.27s	remaining: 2.66s
200:	learn: 4.0899397	total: 1.28s	remaining: 2.66s
201:	learn: 4.0891776	total: 1.29s	remaining: 2.65s
202:	learn: 4.0863949	total: 1.3s	remaining: 2.65s
203:	learn: 4.0848979	total: 1.3s	remaining: 2.64s
204:	learn: 4.0805754	total: 1.31s	remaining: 2.64s
205:	learn: 4.0785773	total: 1.31s	remaining: 2.63s
206:	learn: 4.0738507	total: 1.32s	remaining: 2.63s
207:	learn: 4.0727036	total: 1.33s	remaining: 2.62s
208:	learn: 4.0714249	total: 1.33s	remaining: 2.61s
209:	learn: 4.0702183	total: 1.34s	remaining: 2.61s
210:	learn: 4.0677041	total: 1.35s	remaining: 2.6s
211:	learn: 4.0669937	total: 1.35s	remaining: 2.59s
212:	learn: 4.0660156	total: 1.36s	remaining: 2.59s
213:	learn: 4.0648736	total: 1.37s	remaining: 2.58s
214:	learn: 4.0638679	total: 1.37s	remaining: 2.57s
215:	learn: 4.0627199	total: 1.38s	remaining: 2.57s
216:	learn: 4.0580899	total: 1.39s	remaining: 2.56s
217:	learn: 4.0565189	total: 1.39s	remaining: 2.56s
218:	learn: 4.0520648	total: 1.4s	remaining: 2.55s
219:	learn: 4.0501076	total: 1.4s	remaining: 2.54s
220:	learn: 4.0491974	total: 1.41s	remaining: 2.53s
221:	learn: 4.0477527	total: 1.42s	remaining: 2.53s
222:	learn: 4.0459074	total: 1.42s	remaining: 2.52s
223:	learn: 4.0452585	total: 1.43s	remaining: 2.51s
224:	learn: 4.0438271	total: 1.43s	remaining: 2.5s
225:	learn: 4.0433575	total: 1.44s	remaining: 2.5s
226:	learn: 4.0421785	total: 1.45s	remaining: 2.49s
227:	learn: 4.0410349	total: 1.45s	remaining: 2.48s
228:	learn: 4.0400024	total: 1.46s	remaining: 2.47s
229:	learn: 4.0389714	total: 1.46s	remaining: 2.47s
230:	learn: 4.0383350	total: 1.47s	remaining: 2.46s
231:	learn: 4.0370701	total: 1.47s	remaining: 2.45s
232:	learn: 4.0361365	total: 1.48s	remaining: 2.44s
233:	learn: 4.0332702	total: 1.49s	remaining: 2.44s
234:	learn: 4.0327036	total: 1.49s	remaining: 2.43s
235:	learn: 4.0306031	total: 1.5s	remaining: 2.42s
236:	learn: 4.0262787	total: 1.5s	remaining: 2.42s
237:	learn: 4.0256759	total: 1.51s	remaining: 2.41s
238:	learn: 4.0250432	total: 1.52s	remaining: 2.4s
239:	learn: 4.0222719	total: 1.52s	remaining: 2.4s
240:	learn: 4.0217132	total: 1.53s	remaining: 2.39s
241:	learn: 4.0211840	total: 1.53s	remaining: 2.38s
242:	learn: 4.0205278	total: 1.54s	remaining: 2.38s
243:	learn: 4.0194657	total: 1.54s	remaining: 2.37s
244:	learn: 4.0182280	total: 1.55s	remaining: 2.36s
245:	learn: 4.0173781	total: 1.56s	remaining: 2.35s
246:	learn: 4.0164354	total: 1.56s	remaining: 2.35s
247:	learn: 4.0139817	total: 1.57s	remaining: 2.34s
248:	learn: 4.0130410	total: 1.57s	remaining: 2.33s
249:	learn: 4.0114767	total: 1.58s	remaining: 2.33s
250:	learn: 4.0052660	total: 1.59s	remaining: 2.32s
251:	learn: 4.0045656	total: 1.59s	remaining: 2.31s
252:	learn: 4.0000229	total: 1.6s	remaining: 2.31s
253:	learn: 3.9987282	total: 1.61s	remaining: 2.3s
254:	learn: 3.9964939	total: 1.61s	remaining: 2.29s
255:	learn: 3.9959030	total: 1.62s	remaining: 2.29s
256:	learn: 3.9952957	total: 1.62s	remaining: 2.28s
257:	learn: 3.9921962	total: 1.63s	remaining: 2.27s
258:	learn: 3.9916671	total: 1.63s	remaining: 2.27s
259:	learn: 3.9909041	total: 1.64s	remaining: 2.26s
260:	learn: 3.9903111	total: 1.65s	remaining: 2.25s
261:	learn: 3.9890826	total: 1.65s	remaining: 2.24s
262:	learn: 3.9872598	total: 1.66s	remaining: 2.24s
263:	learn: 3.9859303	total: 1.66s	remaining: 2.23s
264:	learn: 3.9839638	total: 1.67s	remaining: 2.22s
265:	learn: 3.9827296	total: 1.67s	remaining: 2.22s
266:	learn: 3.9822553	total: 1.68s	remaining: 2.21s
267:	learn: 3.9805289	total: 1.69s	remaining: 2.2s
268:	learn: 3.9793172	total: 1.69s	remaining: 2.2s
269:	learn: 3.9779199	total: 1.7s	remaining: 2.19s
270:	learn: 3.9775884	total: 1.71s	remaining: 2.18s
271:	learn: 3.9747151	total: 1.71s	remaining: 2.18s
272:	learn: 3.9741088	total: 1.72s	remaining: 2.17s
273:	learn: 3.9724132	total: 1.72s	remaining: 2.17s
274:	learn: 3.9717089	total: 1.73s	remaining: 2.16s
275:	learn: 3.9708570	total: 1.74s	remaining: 2.15s
276:	learn: 3.9700907	total: 1.74s	remaining: 2.15s
277:	learn: 3.9694553	total: 1.75s	remaining: 2.14s
278:	learn: 3.9687010	total: 1.75s	remaining: 2.13s
279:	learn: 3.9656541	total: 1.76s	remaining: 2.12s
280:	learn: 3.9648753	total: 1.76s	remaining: 2.12s
281:	learn: 3.9635149	total: 1.77s	remaining: 2.11s
282:	learn: 3.9625804	total: 1.78s	remaining: 2.1s
283:	learn: 3.9620035	total: 1.78s	remaining: 2.1s
284:	learn: 3.9611436	total: 1.79s	remaining: 2.09s
285:	learn: 3.9576806	total: 1.79s	remaining: 2.08s
286:	learn: 3.9564956	total: 1.8s	remaining: 2.08s
287:	learn: 3.9552738	total: 1.81s	remaining: 2.07s
288:	learn: 3.9542448	total: 1.81s	remaining: 2.06s
289:	learn: 3.9532040	total: 1.82s	remaining: 2.06s
290:	learn: 3.9523740	total: 1.82s	remaining: 2.05s
291:	learn: 3.9501598	total: 1.83s	remaining: 2.04s
292:	learn: 3.9495551	total: 1.83s	remaining: 2.04s
293:	learn: 3.9485323	total: 1.84s	remaining: 2.03s
294:	learn: 3.9454494	total: 1.85s	remaining: 2.02s
295:	learn: 3.9449381	total: 1.85s	remaining: 2.01s
296:	learn: 3.9441315	total: 1.86s	remaining: 2.01s
297:	learn: 3.9427541	total: 1.86s	remaining: 2s
298:	learn: 3.9415625	total: 1.87s	remaining: 2s
299:	learn: 3.9398531	total: 1.88s	remaining: 1.99s
300:	learn: 3.9396669	total: 1.88s	remaining: 1.98s
301:	learn: 3.9368830	total: 1.89s	remaining: 1.97s
302:	learn: 3.9357680	total: 1.89s	remaining: 1.97s
303:	learn: 3.9350252	total: 1.9s	remaining: 1.96s
304:	learn: 3.9346926	total: 1.91s	remaining: 1.96s
305:	learn: 3.9339057	total: 1.91s	remaining: 1.95s
306:	learn: 3.9327369	total: 1.92s	remaining: 1.94s
307:	learn: 3.9320861	total: 1.92s	remaining: 1.94s
308:	learn: 3.9314997	total: 1.93s	remaining: 1.93s
309:	learn: 3.9310084	total: 1.94s	remaining: 1.92s
310:	learn: 3.9303990	total: 1.94s	remaining: 1.92s
311:	learn: 3.9288671	total: 1.95s	remaining: 1.91s
312:	learn: 3.9286326	total: 1.95s	remaining: 1.9s
313:	learn: 3.9279350	total: 1.96s	remaining: 1.89s
314:	learn: 3.9271563	total: 1.96s	remaining: 1.89s
315:	learn: 3.9247755	total: 1.97s	remaining: 1.88s
316:	learn: 3.9238456	total: 1.97s	remaining: 1.87s
317:	learn: 3.9228557	total: 1.98s	remaining: 1.87s
318:	learn: 3.9214460	total: 1.99s	remaining: 1.86s
319:	learn: 3.9196143	total: 1.99s	remaining: 1.85s
320:	learn: 3.9192593	total: 2s	remaining: 1.85s
321:	learn: 3.9163226	total: 2s	remaining: 1.84s
322:	learn: 3.9155815	total: 2.01s	remaining: 1.84s
323:	learn: 3.9150270	total: 2.02s	remaining: 1.83s
324:	learn: 3.9139959	total: 2.02s	remaining: 1.82s
325:	learn: 3.9129572	total: 2.03s	remaining: 1.82s
326:	learn: 3.9123226	total: 2.03s	remaining: 1.81s
327:	learn: 3.9115180	total: 2.04s	remaining: 1.8s
328:	learn: 3.9099894	total: 2.05s	remaining: 1.8s
329:	learn: 3.9095180	total: 2.05s	remaining: 1.79s
330:	learn: 3.9086597	total: 2.06s	remaining: 1.78s
331:	learn: 3.9080975	total: 2.06s	remaining: 1.78s
332:	learn: 3.9068760	total: 2.07s	remaining: 1.77s
333:	learn: 3.9042830	total: 2.08s	remaining: 1.76s
334:	learn: 3.9015588	total: 2.08s	remaining: 1.76s
335:	learn: 3.9003171	total: 2.09s	remaining: 1.75s
336:	learn: 3.8988757	total: 2.09s	remaining: 1.75s
337:	learn: 3.8983064	total: 2.1s	remaining: 1.74s
338:	learn: 3.8979023	total: 2.1s	remaining: 1.73s
339:	learn: 3.8971121	total: 2.11s	remaining: 1.73s
340:	learn: 3.8960786	total: 2.12s	remaining: 1.72s
341:	learn: 3.8948618	total: 2.13s	remaining: 1.72s
342:	learn: 3.8943933	total: 2.13s	remaining: 1.71s
343:	learn: 3.8927642	total: 2.14s	remaining: 1.7s
344:	learn: 3.8920548	total: 2.14s	remaining: 1.7s
345:	learn: 3.8912723	total: 2.15s	remaining: 1.69s
346:	learn: 3.8904051	total: 2.16s	remaining: 1.68s
347:	learn: 3.8898619	total: 2.16s	remaining: 1.68s
348:	learn: 3.8880610	total: 2.17s	remaining: 1.67s
349:	learn: 3.8876694	total: 2.17s	remaining: 1.67s
350:	learn: 3.8872557	total: 2.18s	remaining: 1.66s
351:	learn: 3.8863696	total: 2.19s	remaining: 1.65s
352:	learn: 3.8849198	total: 2.19s	remaining: 1.65s
353:	learn: 3.8823925	total: 2.2s	remaining: 1.64s
354:	learn: 3.8808695	total: 2.2s	remaining: 1.63s
355:	learn: 3.8785848	total: 2.21s	remaining: 1.63s
356:	learn: 3.8770681	total: 2.21s	remaining: 1.62s
357:	learn: 3.8758965	total: 2.22s	remaining: 1.61s
358:	learn: 3.8746195	total: 2.23s	remaining: 1.61s
359:	learn: 3.8738218	total: 2.23s	remaining: 1.6s
360:	learn: 3.8717754	total: 2.24s	remaining: 1.59s
361:	learn: 3.8709302	total: 2.25s	remaining: 1.59s
362:	learn: 3.8703547	total: 2.25s	remaining: 1.58s
363:	learn: 3.8691391	total: 2.26s	remaining: 1.57s
364:	learn: 3.8673047	total: 2.26s	remaining: 1.57s
365:	learn: 3.8669307	total: 2.27s	remaining: 1.56s
366:	learn: 3.8660647	total: 2.27s	remaining: 1.55s
367:	learn: 3.8635384	total: 2.28s	remaining: 1.55s
368:	learn: 3.8629081	total: 2.29s	remaining: 1.54s
369:	learn: 3.8624236	total: 2.29s	remaining: 1.54s
370:	learn: 3.8615403	total: 2.3s	remaining: 1.53s
371:	learn: 3.8591099	total: 2.31s	remaining: 1.52s
372:	learn: 3.8576565	total: 2.31s	remaining: 1.52s
373:	learn: 3.8573150	total: 2.32s	remaining: 1.51s
374:	learn: 3.8548244	total: 2.32s	remaining: 1.5s
375:	learn: 3.8541381	total: 2.33s	remaining: 1.5s
376:	learn: 3.8506611	total: 2.33s	remaining: 1.49s
377:	learn: 3.8504190	total: 2.34s	remaining: 1.49s
378:	learn: 3.8501521	total: 2.35s	remaining: 1.48s
379:	learn: 3.8467897	total: 2.35s	remaining: 1.47s
380:	learn: 3.8454613	total: 2.36s	remaining: 1.47s
381:	learn: 3.8447129	total: 2.36s	remaining: 1.46s
382:	learn: 3.8441581	total: 2.37s	remaining: 1.45s
383:	learn: 3.8430961	total: 2.38s	remaining: 1.45s
384:	learn: 3.8426787	total: 2.38s	remaining: 1.44s
385:	learn: 3.8422266	total: 2.39s	remaining: 1.44s
386:	learn: 3.8416775	total: 2.39s	remaining: 1.43s

array([[18.6514567 , 20.43345701],
       [17.87152462, 19.03858179],
       [18.39610077, 19.81176165],
       ...,
       [24.89918091, 23.6647663 ],
       [23.61400121, 22.04573985],
       [33.28339336, 32.96339901]], shape=(30156, 2))

In [7]:
def objective(trial):

    with mlflow.start_run(nested=True,run_name=f"trial_{trial.number}"):

        stacking_models = trial.suggest_categorical('stacking_models', ['LR','Lasso','Ridge','DT'])

        if stacking_models == 'LR':
            estimator = LinearRegression()
            
        elif stacking_models == 'DT':

            max_depth = trial.suggest_int('max_depth', 4, 10)
            max_leaf_nodes = trial.suggest_int('max_leaf_nodes', 5, 10)
            min_samples_split = trial.suggest_int('min_samples_split', 5, 20)
            min_samples_leaf = trial.suggest_int('min_samples_leaf', 5, 10)
            max_features = trial.suggest_categorical('max_features', ['sqrt', 'log2', None])

            estimator = DecisionTreeRegressor(max_depth=max_depth, max_leaf_nodes=max_leaf_nodes,
                                            min_samples_split=min_samples_split,
                                            min_samples_leaf=min_samples_leaf,
                                            max_features=max_features, random_state=seed)
        
        elif stacking_models == 'Lasso':

            alpha = trial.suggest_float('alpha', 0.001,0.5, log=True)

            estimator = Lasso(alpha=alpha ,random_state=seed)

        elif stacking_models == 'Ridge':
            alpha = trial.suggest_float('alpha', 0.001,0.5, log=True)
            solver = trial.suggest_categorical('solver', ['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga'])

            estimator = Ridge(alpha=alpha,solver=solver ,random_state=seed)
        
        
        # model = Pipeline([
            # ('preprocessor',preprocessor),
            # ('Stacking_estimator', estimator)
        # ])  

        cv_score = cross_validate(estimator, x_predicted, y_train, cv=KFold(n_splits=5,shuffle=True,random_state=seed), 
                                scoring='neg_mean_absolute_error',verbose=False,n_jobs=-1,return_train_score=True)
        
        trial.set_user_attr('train_cv',np.mean(cv_score['train_score']))
        trial.set_user_attr('val_cv',np.mean(cv_score['test_score']))
        
        mlflow.log_params(trial.params)
        mlflow.log_metric('train_cv_score',np.mean(cv_score['train_score']))
        mlflow.log_metric('val_cv_score',np.mean(cv_score['test_score']))
            
        return np.mean(cv_score['test_score'])


study = optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler(seed=seed),
                            study_name='StackingRegressor Hyperparameter Tuning')
    
with mlflow.start_run(run_name='With numerical cols') as parent :
    study.optimize(objective,n_trials=30,show_progress_bar=True)

    mlflow.log_metric('With numerical cols',study.best_value)
    mlflow.log_params(study.best_params)

    print('Best parameters:', study.best_params)
    print('Best score:', study.best_value)

[I 2026-06-22 21:55:23,400] A new study created in memory with name: StackingRegressor Hyperparameter Tuning

  0%|          | 0/30 [00:00<?, ?it/s]

🏃 View run trial_0 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/378d2df58d1d4986a7aafc1af2aeee1d
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:55:28,442] Trial 0 finished with value: -3.05709812146938 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.013913346327363716}. Best is trial 0 with value: -3.05709812146938.
🏃 View run trial_1 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/1cf7de149fec4493b54f94c1d99f601a
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:55:31,641] Trial 1 finished with value: -3.1872021099877657 and parameters: {'stacking_models': 'DT', 'max_depth': 6, 'max_leaf_nodes': 9, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: -3.05709812146938.
🏃 View run trial_2 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/70309411d45444cd933d11d31f9b0135
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:55:34,613] Trial 2 finished with value: -3.1872021099877657 and parameters: {'stacking_models': 'DT', 'max_depth': 10, 'max_leaf_nodes': 9, 'min_samples_split': 12, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: -3.05709812146938.
🏃 View run trial_3 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/7363cfbaa4444db3a1fc3e4dc27611a7
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:55:36,832] Trial 3 finished with value: -3.0571110516806104 and parameters: {'stacking_models': 'LR'}. Best is trial 0 with value: -3.05709812146938.
🏃 View run trial_4 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/f5baaa69757848599ef679717b246e41
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:55:38,943] Trial 4 finished with value: -3.0571110516806104 and parameters: {'stacking_models': 'LR'}. Best is trial 0 with value: -3.05709812146938.
🏃 View run trial_5 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/feecffd0894240d89181b8ea340c3f0f
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:55:45,165] Trial 5 finished with value: -3.259917214328051 and parameters: {'stacking_models': 'DT', 'max_depth': 8, 'max_leaf_nodes': 7, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 0 with value: -3.05709812146938.
🏃 View run trial_6 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/d97189f2635d468ca26c8d2b9ee0a9ef
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:55:57,134] Trial 6 finished with value: -3.259917214328051 and parameters: {'stacking_models': 'DT', 'max_depth': 7, 'max_leaf_nodes': 7, 'min_samples_split': 20, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 0 with value: -3.05709812146938.
🏃 View run trial_7 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/420f14169692440d85bc7a27a0156b3e
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:56:10,030] Trial 7 finished with value: -3.0571211574847337 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.001985633975248891}. Best is trial 0 with value: -3.05709812146938.
🏃 View run trial_8 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/bdcc627b0b634d5e9a083c2964610943
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:56:17,790] Trial 8 finished with value: -3.0571110516806104 and parameters: {'stacking_models': 'LR'}. Best is trial 0 with value: -3.05709812146938.
🏃 View run trial_9 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/30aca648e7e34fe5a3e78fc633790a22
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:56:33,147] Trial 9 finished with value: -3.0571110427454014 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.4319513210123975, 'solver': 'svd'}. Best is trial 0 with value: -3.05709812146938.
🏃 View run trial_10 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/b03cf61f4ea24462b847040477377813
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:56:41,785] Trial 10 finished with value: -3.0570819984726145 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.02193976099753772}. Best is trial 10 with value: -3.0570819984726145.
🏃 View run trial_11 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/d48d1d54db56412bab3cc74a25e9900f
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:56:49,201] Trial 11 finished with value: -3.0570937441232373 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.016080472463902217}. Best is trial 10 with value: -3.0570819984726145.
🏃 View run trial_12 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/6075709bcfc14f62a6f96d759b408e85
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:56:53,152] Trial 12 finished with value: -3.057065347228273 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.030400330143470662}. Best is trial 12 with value: -3.057065347228273.
🏃 View run trial_13 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/e52fcf0d96d34a1abafce7b90bdd4307
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:57:05,835] Trial 13 finished with value: -3.056973179694535 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.07994066469786422}. Best is trial 13 with value: -3.056973179694535.
🏃 View run trial_14 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/f51e43065e6a4ed997468af40a9cdbf0
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:57:17,168] Trial 14 finished with value: -3.0568528151386962 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.1519156956818942}. Best is trial 14 with value: -3.0568528151386962.
🏃 View run trial_15 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/c0cf39e3f538496ea8ecd83213623a2c
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:57:25,797] Trial 15 finished with value: -3.057111047216766 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.2157958344261921, 'solver': 'cholesky'}. Best is trial 14 with value: -3.0568528151386962.
🏃 View run trial_16 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/f9e7612a8c7f4aa2a2f6f258733ff6e8
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:57:34,155] Trial 16 finished with value: -3.056925888069848 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.10730047879921285}. Best is trial 14 with value: -3.0568528151386962.
🏃 View run trial_17 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/a510a437fab8481cbadad7d31e6ac917
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:57:49,814] Trial 17 finished with value: -3.056898503934006 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.12354200958648551}. Best is trial 14 with value: -3.0568528151386962.
🏃 View run trial_18 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/5718ce8f33d247279111ecacabe695b1
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:58:01,774] Trial 18 finished with value: -3.0569706622963313 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.08135644447758059}. Best is trial 14 with value: -3.0568528151386962.
🏃 View run trial_19 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/42426b8f943249d78c076cd50332cb07
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:58:13,183] Trial 19 finished with value: -3.057112700907252 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.3801301654472159, 'solver': 'saga'}. Best is trial 14 with value: -3.0568528151386962.
🏃 View run trial_20 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/da9f18ae70114b968f68c91eacfeef27
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:58:29,203] Trial 20 finished with value: -3.0571178351326647 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.004153639275003393}. Best is trial 14 with value: -3.0568528151386962.
🏃 View run trial_21 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/0022666ee35c4c6f985e6fd985b48a2e
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:58:35,071] Trial 21 finished with value: -3.0569289503216295 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.10550128137631044}. Best is trial 14 with value: -3.0568528151386962.
🏃 View run trial_22 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/c18dd737d6d649b6bda4c6ec9dd138d9
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:58:38,120] Trial 22 finished with value: -3.0568427321904426 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.1583264262616579}. Best is trial 22 with value: -3.0568427321904426.
🏃 View run trial_23 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/cab1694fb9c349949775780c1d0e53c2
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:58:45,190] Trial 23 finished with value: -3.056789136721678 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.19333927035274068}. Best is trial 23 with value: -3.056789136721678.
🏃 View run trial_24 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/eba606bbd2b04259bf6dd7bab40d0896
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:58:54,519] Trial 24 finished with value: -3.0567490664205264 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.22090191390970296}. Best is trial 24 with value: -3.0567490664205264.
🏃 View run trial_25 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/b97c25a6be79486da89e46edf9aae23a
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:59:09,113] Trial 25 finished with value: -3.0570476114133336 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.03966879562332983}. Best is trial 24 with value: -3.0567490664205264.
🏃 View run trial_26 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/324f85022cea42279e6ed2951e1cd79a
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:59:17,438] Trial 26 finished with value: -3.0567233619688037 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.23980657464134286}. Best is trial 26 with value: -3.0567233619688037.
🏃 View run trial_27 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/791b729bb48a485db07d64d95d83d773
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:59:24,511] Trial 27 finished with value: -3.057111045737775 and parameters: {'stacking_models': 'Ridge', 'alpha': 0.28729218228540004, 'solver': 'lsqr'}. Best is trial 26 with value: -3.0567233619688037.
🏃 View run trial_28 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/05232247e33d4f20ba32680002b0d6cb
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:59:33,794] Trial 28 finished with value: -3.0571110516806104 and parameters: {'stacking_models': 'LR'}. Best is trial 26 with value: -3.0567233619688037.
🏃 View run trial_29 at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/d896c46f456a44d4bbe83c60b390a355
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6
[I 2026-06-22 21:59:45,849] Trial 29 finished with value: -3.057020679098513 and parameters: {'stacking_models': 'Lasso', 'alpha': 0.05403302184800106}. Best is trial 26 with value: -3.0567233619688037.
Best parameters: {'stacking_models': 'Lasso', 'alpha': 0.23980657464134286}
Best score: -3.0567233619688037
🏃 View run With numerical cols at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6/runs/0c22bd9df1b646989b01b3a771a2527e
🧪 View experiment at: https://dagshub.com/shapniljoy/delivery-time-prediction.mlflow/#/experiments/6

In [8]:
study.trials_dataframe()[['user_attrs_train_cv','user_attrs_val_cv','params_stacking_models']].sort_values(by='user_attrs_val_cv',ascending=False)

    user_attrs_train_cv  user_attrs_val_cv params_stacking_models
26            -3.055944          -3.056723                  Lasso
24            -3.055969          -3.056749                  Lasso
23            -3.056009          -3.056789                  Lasso
22            -3.056064          -3.056843                  Lasso
14            -3.056074          -3.056853                  Lasso
17            -3.056122          -3.056899                  Lasso
16            -3.056150          -3.056926                  Lasso
21            -3.056154          -3.056929                  Lasso
18            -3.056197          -3.056971                  Lasso
13            -3.056200          -3.056973                  Lasso
29            -3.056248          -3.057021                  Lasso
25            -3.056276          -3.057048                  Lasso
12            -3.056295          -3.057065                  Lasso
10            -3.056312          -3.057082                  Lasso
11            -3.056323          -3.057094                  Lasso
0             -3.056328          -3.057098                  Lasso
9             -3.056338          -3.057111                  Ridge
27            -3.056338          -3.057111                  Ridge
15            -3.056338          -3.057111                  Ridge
4             -3.056338          -3.057111                     LR
8             -3.056338          -3.057111                     LR
3             -3.056338          -3.057111                     LR
28            -3.056338          -3.057111                     LR
19            -3.056339          -3.057113                  Ridge
20            -3.056348          -3.057118                  Lasso
7             -3.056350          -3.057121                  Lasso
2             -3.167215          -3.187202                     DT
1             -3.167215          -3.187202                     DT
6             -3.235244          -3.259917                     DT
5             -3.235244          -3.259917                     DT

Here, we have taken the out of box predicted values for each model and stacked them together to use as a input variables for the meta model hyperparamters tuning.  
The Optuna tuning resulted into a perfectly fitting model with lasso regression with no gap in the training and validation scores.  
Also it yielded the lowest test score among all the stacking models at MAE = 3.05 minutes.
We will choose this specification with lasso model as meta model to get our final predicted model.